# Setup
title:        123test API
tagline:      API-SDK for 123test API documentation and code examples to fully integrate tests of 123test into websites (both questionnaires and test results).
baseurl:      "/api-sdk"
paginate:     0

# Gems
gems:
#  - jekyll-paginate

#Others
markdown: kramdown
