# Setup
title:        API SDK
tagline:      SDK for the 123test API. Documentation and code examples to fully integrate tests of 123test into websites (both questionnaires and test results).
baseurl:      "/api-sdk"
permalink: pretty
# Gems
gems:
#  - jekyll-paginate

#Others
markdown: kramdown

collections:
  products:
    output: true
